version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies for frontend..."
      - cd frontend
      - npm install
      - echo "Installing dependencies for backend..."
      - cd ../backend
      - npm install
      - echo "Installing dependencies for user-portal-frontend..."
      - cd ../user-portal-frontend
      - npm install
  build:
    commands:
      - echo "Building frontend..."
      - cd ../frontend
      - npm run build
      - echo "Building user-portal-frontend..."
      - cd ../user-portal-frontend
      - npm run build
      - echo "Running tests for backend..."
      - cd ../backend
      - npm run test
  post_build:
    commands:
      - echo "Build completed."
artifacts:
  files:
    - '**/*'
    - 'frontend/build/**/*'
    - 'user-portal-frontend/build/**/*'
  discard-paths: yes
cache:
  paths:
    - 'frontend/node_modules/**/*'
    - 'backend/node_modules/**/*'
    - 'user-portal-frontend/node_modules/**/*'

