version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - cd admin-portal-frontend && npm install
      - cd ../examportalbackend && npm install
  build:
    commands:
      - echo Building admin-portal-frontend...
      - cd ../admin-portal-frontend && npm run build
      - echo Running tests for examportalbackend...
      - cd ../examportalbackend && npm run test
  post_build:
    commands:
      - echo Build completed.
artifacts:
  files:
    - '**/*'
    - 'admin-portal-frontend/build/**/*'
  discard-paths: yes
cache:
  paths:
    - 'admin-portal-frontend/node_modules/**/*'
    - 'examportalbackend/node_modules/**/*'
